name: CI/CD Pipeline

on:
  push:
    branches: [main]

# Pakai env variable ini buat maksa pake Node 24 sesuai saran GitHub
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: "24" # Update ke 24 biar aman sampai akhir 2026
          cache: "npm"

      - name: Install Dependencies
        # Ganti path ini sesuai nama folder frontend lo
        run: cd apps/frontend && npm install

      - name: Type Check & Build
        # Masuk ke folder dulu baru jalanin npm run build
        run: cd apps/frontend && npm run build
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
